# Generated by Django 3.0.7 on 2022-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Clave', models.CharField(max_length=20)),
                ('Telefono', models.PositiveIntegerField()),
                ('Genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
            ],
        ),
    ]
