# Generated by Django 3.0.7 on 2022-09-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaludEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Usuario')),
            ],
        ),
    ]
