# Generated by Django 3.0.7 on 2022-09-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaludEnCasa', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id_Registro_Historia', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Fecha_Registro_HC', models.DateField(auto_now=True)),
                ('Detalles', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_Sugerencia', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Fecha_Sugerencia', models.DateField(auto_now=True)),
                ('Sugerencia', models.CharField(max_length=5000)),
                ('id_Registro_Historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Historia_Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Signos_Vitales',
            fields=[
                ('idRegistro', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Signo_Vital', models.CharField(choices=[('O', 'Oximetría'), ('R', 'Frecuencia respiratoria'), ('C', 'Frecuencia cardiaca'), ('T', 'Temperatura'), ('A', 'Presion arterial'), ('G', 'Glicemias')], max_length=1)),
                ('Valor_Signo', models.FloatField()),
                ('Fecha_Registro', models.DateField(auto_now=True)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=50)),
                ('Registro', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Personal_Salud')),
            ],
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='idMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Medico'),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Paciente'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parentesco', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Paciente')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Personal_Salud')),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='idMedico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Medico'),
            preserve_default=False,
        ),
    ]
