# Generated by Django 3.0.7 on 2022-09-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaludEnCasa', '0003_auto_20220911_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idMedico',
        ),
    ]
