# Generated by Django 3.0.7 on 2022-09-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaludEnCasa', '0004_remove_paciente_idmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idMedico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SaludEnCasa.Medico'),
            preserve_default=False,
        ),
    ]
