# Generated by Django 3.0.7 on 2022-09-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludEnCasa', '0005_paciente_idmedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='id_Registro_Historia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='idRegistro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
